In [1]:
import numpy as np
import pandas as pd

__加载数据__

In [2]:
# 加载训练数据
train_data = pd.read_csv("mnist_train.csv").values
# 加载测试数据
test_data = pd.read_csv("mnist_test.csv").values

# 将数据分解成特征X，与类别标签Y
train_x = train_data[:, 1:]
train_y = train_data[:, 0]
test_x = test_data[:, 1:]
test_y = test_data[:, 0]
train_x, train_y, test_x, test_y

(array([[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ..., 
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]], dtype=int64),
 array([0, 4, 1, ..., 5, 6, 8], dtype=int64),
 array([[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ..., 
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]], dtype=int64),
 array([2, 1, 0, ..., 4, 5, 6], dtype=int64))

#### Sigmoid函数

In [13]:
def sigmoid(z):
    return 1 / (1 + np.exp(-z))

__构造受限玻尔兹曼机（RBM）__

In [41]:
# 受限玻尔兹曼机（RBM）类
class RBM:
    def __init__(self, size=[], learning_rate=0.01, numepochs=1):
        #{W, b, c}为参数，W为神经元相连接的权重，b为显示层的偏置值，c为隐藏层的偏置值
        self.W = np.zeros(size)
        self.b = np.zeros((1, size[0]))
        self.c = np.zeros((1, size[1]))
        
        self.learning_rate = learning_rate
        self.numepochs = numepochs
    
    # RBM 训练
    def train(self, X):
        print('begin train , X.shape',X.shape,'numepochs:',self.numepochs)
        m, n = X.shape
        for i in range(self.numepochs):
            for x in X:
                v1 = x.reshape(1, n)
                h1 = sigmoid(self.c + v1.dot(self.W))
                v2 = sigmoid(self.b + h1.dot(self.W.T))
                h2 = sigmoid(self.c + v2.dot(self.W))
                
                a1 = v1.T.dot(h1)
                a2 = v2.T.dot(h2)
                
                self.W = self.W + self.learning_rate * (a1 - a2)
                self.b = self.b + self.learning_rate * (v1 - v2)
                self.c = self.c + self.learning_rate * (h1 - h2)
                
        return self.b, self.c

In [42]:
rbm = RBM(size=[28*28, 10],learning_rate=0.01)
rbm.train(train_x[:100, :] / 255.0)

begin train , X.shape (100, 784) numepochs: 1


(array([[-0.3207177 , -0.3207177 , -0.3207177 , -0.3207177 , -0.3207177 ,
         -0.3207177 , -0.3207177 , -0.3207177 , -0.3207177 , -0.3207177 ,
         -0.3207177 , -0.3207177 , -0.3207177 , -0.3207177 , -0.3207177 ,
         -0.3207177 , -0.3207177 , -0.3207177 , -0.3207177 , -0.3207177 ,
         -0.3207177 , -0.3207177 , -0.3207177 , -0.3207177 , -0.3207177 ,
         -0.3207177 , -0.3207177 , -0.3207177 , -0.3207177 , -0.3207177 ,
         -0.3207177 , -0.3207177 , -0.3207177 , -0.3207177 , -0.3207177 ,
         -0.3207177 , -0.3207177 , -0.3207177 , -0.3207177 , -0.3207177 ,
         -0.3207177 , -0.3207177 , -0.3207177 , -0.3207177 , -0.3207177 ,
         -0.3207177 , -0.3207177 , -0.3207177 , -0.3207177 , -0.3207177 ,
         -0.3207177 , -0.3207177 , -0.3207177 , -0.3207177 , -0.3207177 ,
         -0.3207177 , -0.3207177 , -0.3207177 , -0.3207177 , -0.3207177 ,
         -0.3207177 , -0.3207177 , -0.3207177 , -0.3207177 , -0.3207177 ,
         -0.3207177 , -0.3207177 , -0.

__构造深度置信网络（DBN）__

In [ ]:
class DBN:
    def __init__(self):
        pass
    pass